[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "f59936964b519c952bb45f42f099eacc96b53a73"
os = "macos"

    [[squashfs_tools.download]]
    sha256 = "f0a716f9ac6c0fe735ee93dcbdb0cf3e2f0402e9b01786d75d18dd8625a4d5ef"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.aarch64-apple-darwin.tar.gz"
[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "b3e5d41e51b8be9598f106ca8bcffd95b21637dc"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "43b765a48991533d71f7c556c657bae1a3b05ddb0c7e73b256620d38c71a057a"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.aarch64-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "cd559da53a27eb4a114f33ee14ebf7002c6da8e3"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "b1b74b3b7af2f0fd7e0bdbe4163131aedaaa2e47b2fdfff5a66f4b54504589fc"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.aarch64-linux-musl.tar.gz"
[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "209ec058685f934fef1354189d0adf8bfcf5c9f6"
os = "freebsd"

    [[squashfs_tools.download]]
    sha256 = "5ac8aeb6886b723b016127ceddf1b9f54f50884ddc98bbf187db1d70e3fa9ffe"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.aarch64-unknown-freebsd.tar.gz"
[[squashfs_tools]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d5ce5f2071a8fbebdc028f518c5a51538c357f8f"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "aaaf1283adf3ce5c59845fc5a0d6a8e132c736fce477bdbde857e41978c59f3a"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.armv6l-linux-gnueabihf.tar.gz"
[[squashfs_tools]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4db0e99a6a973f657757e6d80ded64bc8a5e31dd"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "6a42c3a2180cb6089e1ee962607b570ecb9b8e622b27f9b6055283b45def34a2"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.armv6l-linux-musleabihf.tar.gz"
[[squashfs_tools]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ecd0c358dc17703506bb76b040e7ca0168da310f"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "4c63af64ef4956c06c2f2adadc78f2431200fe017432e664bcf1fa8cbfe28731"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.armv7l-linux-gnueabihf.tar.gz"
[[squashfs_tools]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df92b301e05f9002ff9bde585000fbecce85fd8d"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "8e989f826e8d6811ce773f5594eed510b2664175ed38725ab5592d0c1fa6e6a8"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.armv7l-linux-musleabihf.tar.gz"
[[squashfs_tools]]
arch = "i686"
git-tree-sha1 = "1aec1ce263832731ad7e72d7c6f858836a8607da"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "081aaa687729c267cad75c95f755f1f87190dc9355fd1548252ea76f28c2b84d"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.i686-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "i686"
git-tree-sha1 = "05c513fe687256dd7d9da59a08c877b61712bc20"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "5934aa129809840712a3ff488ff6c5286b40266c70ec40a3ec7d9a7e6b7c1c91"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.i686-linux-musl.tar.gz"
[[squashfs_tools]]
arch = "powerpc64le"
git-tree-sha1 = "a071dd5842fa8fb77796e1a7fdfbe1887a45a92a"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "933d7527e9947b309d9c8a7cc091e9f280e26682d326c9d8d62ab604eb1ea07d"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.powerpc64le-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "riscv64"
git-tree-sha1 = "27482f8250c61e59dade4900d3cceb8a82bf5e68"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "c39f9614c65821de41899f0ba45aab99d634ca64dc3e17c9300eada0f89c934c"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.riscv64-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "7512d00e9a579e9967eabd941e40b7a28ce94f1e"
os = "macos"

    [[squashfs_tools.download]]
    sha256 = "6cdb72d853acb094f3120fed71d666cb42f0145ce5cf4d4767101ee1b7dcb5c1"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.x86_64-apple-darwin.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "259d0447c108f3c86d7181efc086374a1c94a8a4"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "b1a2751d3ecf3f55a4b099eaa3cc5a23631cde087f5c30017809394717da2bfe"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.x86_64-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "ca02998d8e2d0c4be98b9cf8b463c559a8e6b9ff"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "5157c1f0073143ea41d693880832b4aed2945cfc3595ce09d5152b7de14ef042"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.x86_64-linux-musl.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "d4f94b5706f4ea7a18165899c84ec7f56524665a"
os = "freebsd"

    [[squashfs_tools.download]]
    sha256 = "75a06b263979e9cf823a998786faa090d5aba2fbf55ce624f8d4557483ca984d"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.2+0/squashfs_tools.v4.7.2.x86_64-unknown-freebsd.tar.gz"
